#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-kv-export-worker"
main = "src/index.ts"
compatibility_date = "2024-08-06"

[[kv_namespaces]]
binding = "KV"
id = "8d7cef3a2ee94488acdfa1551bf78fbe"
